
storage:
  type: oci
  bucket: MLOpsDatasets

mongodb:
  database: llm_test_db
  uri: ""
  pem: "mongo.pem"
  ca: "rootCA.crt"

oci:
  user: ''
  fingerprint: ''
  key_file: ''
  tenancy: ''
  region: ''